### ISSUE TITLE
flashlog - write to stdout

### ISSUE THREAD

**Issue by raul-gherman** [JunbeomL22/flashlog#2]
Hi @JunbeomL22 ,

Love this crate, would like to use it in containerised workloads.
In order to achieve that, I could use this superfast logging crate to write to stdout (console), in order for orchestration runtime to pick up logs from containerisation runtime.

Do you think this could be an option?

Best,

Raul

**Comment by JunbeomL22** [comment]
Hi Raul,

I think that could be a good option.

Currently, our logging system writes logs to a file by default. To make it more suitable for your use case, would it be helpful if we make file writing optional?

(In case you might have missed this part, I'd like to mention that the option to write to the console is already available through the with_console_report option - please refer the README)

Thank you for your feedback!

**Comment by raul-gherman** [comment]
Hi @JunbeomL22 ,

Thank you for your swift reply.
Yea, most likely I missed something...

the following code taken from the sample in the Readme does not produce any outcome (does not print anything to console):

```rust
use flashlog::{info, LogLevel, Logger};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let logger = Logger::initialize()
        // .with_file("logs", "message")?
        .with_console_report(true)
        .with_max_log_level(LogLevel::Info)
        .launch();

    info!("Hello, FlashLog!");

    Ok(())
}
``` 

Removing the comment on line 5 has the effect of creating the file in `logs` folder (obviously), with the following content:

```javascript
{"data":{"text":"Hello, FlashLog!"},"date":"20240912","level":"Info","offset":0,"src":"src/main.rs:10","time":"10:30:12.975:488:132","topic":"not given"}
``` 

still, nothing printed to console...
maybe there is something more that I am missing... :/

Best,

Raul

**Comment by JunbeomL22** [comment]
Hi @raul-gherman 

I see. The default setting of the logger was file report. I just updated to version 0.1.3, and in this version, both file and console have been changed to options. Would you like to update flashlog and try running it again exactly as you wrote it? If you run it with the options you specified using version 0.1.3, it will output only to the console.

Please try it out and let me know your feedback.

Best
Junbeom

**Comment by raul-gherman** [comment]
hi @JunbeomL22 ,

proceeded as per your instructions, here is the result:

Cargo.toml:
```rust
[package]
name = "x"
version = "0.1.0"
edition = "2021"

[dependencies]
flashlog = "0.1.3"
```

main.rs:
```rust
use flashlog::{info, LogLevel, Logger};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let logger = Logger::initialize()
        // .with_file("logs", "message")?
        .with_console_report(true)
        .with_max_log_level(LogLevel::Info)
        .launch();

    info!("Hello, FlashLog!");

    Ok(())
}
``` 

output:
```rust
raul@192 x % cargo upgrade
    Updating 'https://github.com/rust-lang/crates.io-index' index
    Checking x's dependencies
name     old req compatible latest new req
====     ======= ========== ====== =======
flashlog 0.1.2   0.1.3      0.1.3  0.1.3  
   Upgrading recursive dependencies
     Locking 0 packages to latest compatible versions
note: pass `--verbose` to see 3 unchanged dependencies behind latest
raul@192 x % cargo run
   Compiling chrono-tz-build v0.4.0
   Compiling chrono-tz v0.10.0
   Compiling flashlog v0.1.3
   Compiling x v0.1.0 (/Users/raul/Desktop/x)
warning: unused variable: `logger`
 --> src/main.rs:4:9
  |
4 |     let logger = Logger::initialize()
  |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_logger`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: `x` (bin "x") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.94s
     Running `target/debug/x`
raul@192 x % 
```

Best,

Raul
```

**Comment by JunbeomL22** [comment]
@raul-gherman 

```Rust
use flashlog::{info, LogLevel, Logger, flushing_log_info, get_unix_nano};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let _logger = Logger::initialize()
        // .with_file("logs", "message")?
        .with_console_report(true)
        .with_max_log_level(LogLevel::Info)
        //.with_msg_buffer_size(1_000_000)
        //.with_msg_flush_interval(1_000_000)
        .launch();

    info!("Hello, world!");
    flushing_log_info!("flushing", unix_nano = get_unix_nano());

    Ok(())
}
```
I see the problem. The logger flushes not everytime but when certain conditions are met for msg queue. In the commenting part, ```with_msg_buffer_size``` sets the maximum length of the beffer and ```with_msg_fliush_interval``` is the time between the flushing. 

The problem is that the program finishes before the conditions are met. This is a kind of a bug. I will fix this bug that the msgs will be flushed in the dropping the guard (in the next update). For the time being, please use ```flushing_log_info``` This pushes msgs regardless of condition. 

Thank you for your feedback. 

Junbeom

**Comment by raul-gherman** [comment]
in the form presented now I confirm it prints to console, good job!

how often does `flushing_log_info` need to be called? after every logging operation? at the end of each function?
can this call be embedded in `info!`, `error!`, etc?

**Comment by JunbeomL22** [comment]
> can this call be embedded in `info!`, `error!`, etc?

Yes. For example, flushing_log_info <- This  has two functinos: logging info then pushing accumulated messages. So it flushes not only info messages but also any level behind the max level msg.



> how often does `flushing_log_info` need to be called? after every logging operation? at the end of each function?

at the place where you have to see log message + at the end of main function. This should be okay
